# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-31 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_layers_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
