# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-31 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_auto_20171231_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='layers',
            name='SPT_N_Value',
            field=models.IntegerField(default=0),
        ),
    ]
